### ISSUE TITLE
Add links to Clipper and Audiogrammer to myradio

### ISSUE THREAD

**Issue by alyxbb** [UniversityRadioYork/MyRadio#1184]
We need links to https://clipper.ury.org.uk/ and https://audiogrammer.ury.org.uk/ somewhere on myradio. Could be on the front page or on SIS.

**Comment by ColinRoitt** [comment]
Just quick note I'm not sure the deployment of audiogrammer currently works so we may want to hold off on this while this is resolved.

**Comment by ColinRoitt** [comment]
Actually, this might be cursed, but should we embed Clipper in a SIS tab since it's a show activity or just link to it?

**Comment by CodingWithError** [comment]
Can you give me some more information and can you assign this to me

**Comment by JP5457** [comment]
> Can you give me some more information and can you assign this to me

I've assigned it to you now. I'm assuming you're new so there's quite a bit of context you're going to need.

Clipper is a new tool that can be used to make snippets from shows. You can find it at clipper.ury.org.uk and at the moment the url is the only way to get to it. Myradio is our management system that society members can use to plan shows, organise the schedule, upload music and various other things. One page of my radio is SIS (studio information service) which is a page that presenters/producers get up while they're doing their shows so that they can see announcements, tracklisting and messages. In order to make clipper more accessible we want a link to it somewhere on the SIS page. This should be quite a simple task as it should hopefully just involve adding a little bit of template code. The main bulk of the task will be getting a myradio development instance setup locally.

You can find the myradio project here: https://github.com/UniversityRadioYork/MyRadio I recommend using docker to run it locally.

If you have any questions you can ask them in the computing channels in our slack server ury.slack.com or you can come and ask them in person at our computing meeetings which are 7pm every wednesday. (I think they're in slb/207 but its best you join the slack for announcements as the room changes sometimes). Good luck and let us know if you have any problems!

**Comment by ColinRoitt** [comment]
https://github.com/UniversityRadioYork/MyRadio/pull/1195 now links to Clipper on the main menu page of myradio but there is still value in embedding this into SIS somehow. 
Also audiogrammer remains an open issue - Due to its state of deployment I propose we create a new ticket for that on it's own so this can be closed.
